export const GET_MISSION_CONTENT = "GET_MISSION_CONTENT";
export const GET_MISSION_CONTENT_SUCCESS = "GET_MISSION_CONTENT_SUCCESS";
export const GET_MISSION_CONTENT_FAILUIRE = "GET_MISSION_CONTENT_FAILUIRE";
