export const FORGOT_PASSWORD_START = "FORGOTPASSWOR_START";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
export const FORGOT_PASSWORD_RESET_STATE = "FORGOT_PASSWORD_RESET_STATE";
