export const GET_SINGLE_PROJECT = "GET_SINGLE_PROJECT";
export const GET_SINGLE_PROJECT_SUCCESS = "GET_SINGLE_PROJECT_SUCCESS";
export const GET_SINGLE_PROJECT_FAILURE = "GET_SINGLE_PROJECT_FAILURE";
