export const strings = {
  AlreadyAC: "I already have an account",
  AccountDetails: "Account details",
  AFew: "A few more details about you please.",
  AndHow: "And how many people work at [company name]?",
  SingUpText: "Make a real difference and meet your ESG goals.",
  SignUpFailed: "SignUp Failed",
  CreateAnAC: "Create an account",
  CreateAC: "Create account",
  CompanyDetails: "Company details",
  CompanyDetails: "Company details",
  CompanySize: "Company size",
  LinkedIn: "Sign up with LinkedIn",
  YouESG: "You, carbon, and ESG",
  PleaseTell:
    "Please tell us about your part in [company name]’s environmental and sustainability goals?",
  Yourname: "Your name",
  LinkedIn: "Sign up with LinkedIn",
  Google: "Sign up with Google",
  Apple: "Sign up with Apple",
  emailPlaceholder: "Input email here",
  UserID: "Your user ID (usually your email)",
  YourPassword: "Your password",
  Forgot: "I forgot my user ID or password",
  VerifyEmail: "Verify Email",
  SignUpEmail: "Sign up with email",
  SingIN: "Sign in",
  Next: "Next",
  Skip: "Skip",
  email: "Email",
  CompanyDetailsText: "Company / organisation name",
  Password: "Password (min. 6 characters)",
  Thanks:
    "Thanks!  We’ve just sent you a verification email.  You don’t need to do anything with that yet.    ",

  FirstName: "Firstname",
  LastName: "Lastname",
  CompanyDetailsInfo:
    "Hi [Tariq], it’s great to have you on board.  Please tell us a little more.  This info helps us configure Decarbonizer just for you.",
  TourText:
    "Congratulations [Tariq]!  You’re now ready to start using Decarbonizer to help [company name] make a real impact.",
  NextTour: "To get you started, we’ve put together a quick app tour for you.",
  TakeTheTour: "Take the tour",
  SkiptheTour: "Skip the tour",
  PleaseSingin: "Please sign in using the details you registered beforehand.",
  InternetIssue: "Internet Issue",
  ReconnectToTheNetwork: "Reconnect to the network",
};

export const IF_OS_IS_IOS = Platform.OS === "ios";
